# GNOME Desktop environment
[Output]
Format=directory

[Content]
Packages=gnome-shell
          gnome-terminal
          gnome-control-center
          gnome-calculator
          gnome-clocks
          gnome-weather
          gnome-logs
          gnome-camera
          eog
          totem
          rhythmbox
